// Admin content strings - Portuguese (Brazil)
// Centralized content for easy translation and maintenance

export const adminContent = {
    dashboard: {
        title: 'Dashboard',
        subtitle: 'Visão geral do seu site',
        stats: {
            publishedPosts: 'Posts publicados',
            draftPosts: 'Rascunhos',
            scheduledPosts: 'Agendados',
            mediaItems: 'Itens de mídia',
            aiGenerations: 'Gerações de IA (este mês)',
        },
        recentPosts: {
            title: 'Posts recentes',
            viewAll: 'Ver todos',
            noPosts: 'Nenhum post ainda',
            createFirst: 'Criar primeiro post',
        },
        quickActions: {
            title: 'Ações rápidas',
            newPost: 'Novo post',
            newLandingPage: 'Nova landing page',
            uploadMedia: 'Upload de mídia',
            viewSite: 'Ver site',
        },
        activity: {
            title: 'Atividade recente',
            noActivity: 'Nenhuma atividade recente',
        },
    },
    posts: {
        title: 'Posts',
        subtitle: 'Gerencie seu conteúdo',
        newPost: 'Novo post',
        editPost: 'Editar Post',
        noPosts: 'Nenhum post encontrado',
        table: {
            title: 'Título',
            status: 'Status',
            author: 'Autor',
            date: 'Data',
            actions: 'Ações',
        },
        status: {
            draft: 'Rascunho',
            published: 'Publicado',
            scheduled: 'Agendado',
            archived: 'Arquivado',
            trashed: 'Lixeira',
        },
        empty: {
            title: 'Nenhum post encontrado',
            description: 'Comece criando seu primeiro post.',
            action: 'Criar post',
        },
        editor: {
            titlePlaceholder: 'Título do post',
            slugLabel: 'Slug (URL)',
            excerptLabel: 'Resumo',
            contentLabel: 'Conteúdo',
            seoTitle: 'Título SEO',
            seoDescription: 'Meta Description',
            categories: 'Categorias',
            tags: 'Tags',
            quickActions: 'Ações Rápidas',
            publishNow: 'Publicar agora',
            unpublish: 'Voltar para rascunho',
            archive: 'Arquivar',
            moveToTrash: 'Mover para lixeira',
            save: 'Salvar',
            saved: 'Salvo!',
            viewPost: 'Ver post',
            backToList: 'Voltar para lista',
        },
        create: {
            title: 'Criar Novo Post',
            subtitle: 'Digite o título para criar um novo rascunho',
            titleLabel: 'Título do post',
            titlePlaceholder: 'Ex: 10 estratégias para crescer seu negócio',
            slugHint: 'O slug (URL) será gerado automaticamente a partir do título',
            createButton: 'Criar rascunho',
            tips: {
                title: 'Dicas para um bom título',
                tip1: 'Seja específico e claro sobre o assunto do post',
                tip2: 'Use palavras-chave relevantes para SEO',
                tip3: 'Evite títulos muito longos (ideal: 50-60 caracteres)',
                tip4: 'Você pode editar o título depois de criar o rascunho',
            },
        },
    },
    landingPages: {
        title: 'Landing Pages',
        subtitle: 'Crie páginas de alta conversão',
        newPage: 'Nova landing page',
        table: {
            title: 'Título',
            status: 'Status',
            slug: 'URL',
            date: 'Data',
            actions: 'Ações',
        },
        empty: {
            title: 'Nenhuma landing page encontrada',
            description: 'Crie sua primeira landing page.',
            action: 'Criar landing page',
        },
    },
    media: {
        title: 'Mídia',
        subtitle: 'Gerencie seus arquivos',
        upload: 'Upload',
        folders: 'Pastas',
        allFiles: 'Todos os arquivos',
        newFolder: 'Nova pasta',
        files: 'arquivos',
        file: 'arquivo',
        viewMode: {
            grid: 'Grade',
            list: 'Lista',
        },
        uploadDialog: {
            title: 'Upload de arquivos',
            dropzone: 'Arraste arquivos aqui ou clique para selecionar',
            dropzoneHint: 'Imagens, vídeos, documentos até 50MB',
            selectedFiles: 'Arquivos selecionados',
            send: 'Enviar',
            sending: 'Enviando...',
            cancel: 'Cancelar',
        },
        folderDialog: {
            title: 'Nova pasta',
            nameLabel: 'Nome da pasta',
            namePlaceholder: 'Ex: Imagens do blog',
            create: 'Criar pasta',
            creating: 'Criando...',
            nameRequired: 'Nome da pasta é obrigatório',
            nameTooShort: 'Nome deve ter pelo menos 2 caracteres',
            invalidChars: 'Nome contém caracteres inválidos',
        },
        sidebar: {
            title: 'Detalhes',
            altTextLabel: 'Texto Alternativo',
            altTextPlaceholder: 'Descrição da imagem para SEO',
            titleLabel: 'Título',
            titlePlaceholder: 'Título do arquivo',
            descriptionLabel: 'Descrição',
            descriptionPlaceholder: 'Descrição detalhada',
            saveChanges: 'Salvar alterações',
            saving: 'Salvando...',
            saved: 'Salvo!',
            openFile: 'Abrir',
            deleteFile: 'Excluir',
            meta: {
                originalName: 'Nome original',
                type: 'Tipo',
                size: 'Tamanho',
                dimensions: 'Dimensões',
                uploadedAt: 'Enviado em',
            },
        },
        confirmDelete: 'Tem certeza que deseja excluir este arquivo?',
        empty: {
            title: 'Nenhum arquivo',
            description: 'Faça upload de imagens, vídeos e documentos.',
            action: 'Fazer upload',
        },
        errors: {
            noFile: 'Nenhum arquivo selecionado',
            uploadFailed: 'Erro ao fazer upload do arquivo',
            updateFailed: 'Erro ao atualizar arquivo',
            deleteFailed: 'Erro ao excluir arquivo',
            folderCreateFailed: 'Erro ao criar pasta',
        },
    },
    users: {
        title: 'Usuários',
        subtitle: 'Gerencie os usuários do painel administrativo',
        newUser: 'Novo usuário',
        noUsers: 'Nenhum usuário encontrado',
        userFound: 'usuário encontrado',
        usersFound: 'usuários encontrados',
        editUser: 'Editar usuário',
        changeRole: 'Alterar função',
        role: 'Função',
        table: {
            name: 'Nome',
            email: 'E-mail',
            role: 'Função',
            status: 'Status',
            actions: 'Ações',
        },
        roles: {
            super_admin: 'Super Admin',
            admin: 'Admin',
            editor: 'Editor',
            author: 'Autor',
            viewer: 'Visualizador',
        },
        permissions: {
            title: 'Permissões',
            description: 'Cada função tem diferentes níveis de acesso ao painel.',
        },
    },
    settings: {
        title: 'Configurações',
        general: {
            title: 'Configurações Gerais',
            subtitle: 'Configure as informações do site',
        },
        seo: {
            title: 'Configurações de SEO',
            subtitle: 'Otimização para mecanismos de busca',
        },
        analytics: {
            title: 'Configurações de Analytics',
            subtitle: 'Acompanhe métricas e desempenho',
        },
        integrations: {
            title: 'Integrações',
            subtitle: 'Conecte com serviços externos',
        },
        webhooks: {
            title: 'Webhooks',
            subtitle: 'Configure notificações e automações',
        },
    },
    generic: {
        loading: 'Carregando...',
        error: 'Ocorreu um erro',
        save: 'Salvar',
        saved: 'Salvo!',
        cancel: 'Cancelar',
        delete: 'Excluir',
        edit: 'Editar',
        create: 'Criar',
        search: 'Buscar',
        filter: 'Filtrar',
        actions: 'Ações',
        confirm: 'Confirmar',
        back: 'Voltar',
        next: 'Próximo',
        previous: 'Anterior',
        showing: 'Mostrando',
        of: 'de',
        results: 'resultados',
        noResults: 'Nenhum resultado encontrado',
    },
    auth: {
        login: {
            title: 'Acesso Admin',
            subtitle: 'Entre com suas credenciais',
            email: 'E-mail',
            password: 'Senha',
            submit: 'Entrar',
            forgotPassword: 'Esqueceu a senha?',
            error: {
                invalidCredentials: 'E-mail ou senha inválidos',
                generic: 'Ocorreu um erro ao fazer login',
            },
        },
        logout: 'Sair',
    },
    ai: {
        panel: {
            title: 'Gerador de IA',
            toggleOpen: 'Abrir painel',
            toggleClose: 'Fechar painel',
        },
        source: {
            title: 'Fonte de conteúdo',
            manual: 'Manual',
            instagram: 'Instagram',
            youtube: 'YouTube',
        },
        url: {
            instagramLabel: 'URL do Instagram',
            youtubeLabel: 'URL do YouTube',
            instagramPlaceholder: 'https://instagram.com/p/...',
            youtubePlaceholder: 'https://youtube.com/watch?v=...',
            scrapeSuccess: 'Conteúdo extraído com sucesso',
            scrapeError: 'Erro ao extrair conteúdo',
        },
        topic: {
            label: 'Assunto / Tema',
            placeholder: 'Descreva o assunto do artigo...',
        },
        type: {
            label: 'Tipo de conteúdo',
            full: 'Artigo completo',
            intro: 'Introdução',
            conclusion: 'Conclusão',
            rewrite: 'Reescrever seleção',
        },
        tone: {
            label: 'Tom de voz',
            professional: 'Profissional',
            casual: 'Informal',
            academic: 'Acadêmico',
            journalistic: 'Jornalístico',
            persuasive: 'Persuasivo',
            educational: 'Educativo',
        },
        length: {
            label: 'Tamanho',
            short: 'Curto (300-500 palavras)',
            medium: 'Médio (700-1000 palavras)',
            long: 'Longo (1500-2500 palavras)',
            veryLong: 'Muito longo (3000-5000 palavras)',
        },
        audience: {
            label: 'Público-alvo',
            placeholder: 'Ex: Empreendedores, gestores de TI...',
        },
        keywords: {
            label: 'Palavras-chave',
            placeholder: 'Adicionar palavra-chave',
            addButton: 'Adicionar',
        },
        instructions: {
            label: 'Instruções adicionais',
            placeholder: 'Quaisquer instruções extras para a IA...',
        },
        actions: {
            generate: 'Gerar conteúdo',
            generating: 'Gerando...',
            insert: 'Inserir no editor',
            regenerate: 'Regenerar',
        },
        preview: {
            title: 'Conteúdo gerado',
        },
        errors: {
            generationFailed: 'Erro ao gerar conteúdo',
            noTopic: 'Por favor, forneça um assunto ou tema',
        },
        assistantButton: 'Assistente IA',
        assistantButtonClose: 'Fechar IA',
    },
    seo: {
        title: 'SEO',
        score: 'Pontuação SEO',
        scoreExcellent: 'Excelente!',
        scoreGood: 'Bom, mas pode melhorar',
        scoreNeedsWork: 'Precisa de melhorias',
        metaTitle: 'Título SEO',
        metaTitlePlaceholder: 'Título para mecanismos de busca',
        metaDescription: 'Meta Description',
        metaDescriptionPlaceholder: 'Descrição para mecanismos de busca',
        keywords: 'Palavras-chave focais',
        keywordsPlaceholder: 'Adicionar palavra-chave',
        keywordsAdd: 'Adicionar',
        keywordsSuggestions: 'Sugestões:',
        generateWithAI: 'Gerar SEO com IA',
        analyzing: 'Analisando...',
        checks: 'Verificações',
        readability: 'Legibilidade',
        readabilityScore: 'Pontuação:',
        avgSentenceLength: 'Sentenças médias:',
        keywordDensity: 'Densidade de palavras-chave',
        googlePreview: 'Preview no Google',
        refreshAnalysis: 'Atualizar análise',
        characters: 'caracteres',
        recommended: 'recomendado',
        words: 'palavras',
    },
} as const

// Type for content structure
export type AdminContent = typeof adminContent
